### PR TITLE
RTL v0.12.3.3: update dependencies to accept lnd v0.15.0

### PR DESCRIPTION
**Pull request by islandbitcoin**
- [x] #20 

The other two issues on this service are bigger ones, so I think this update can go by itself. 
@chrisguida lemme know if you think otherwise or if you want to tackle the two issues assigned to you in this update.

### CODE REVIEW

**Comment by chrisguida** [comment]
Fine to push this out if it's holding things up, I don't think i'll be able to complete the other issues soon

**Comment by chrisguida** [comment]
JK, I fixed this one https://github.com/Start9Labs/ride-the-lightning-wrapper/pull/22

**Comment by islandbitcoin** [comment]
> JK, I fixed this one #22

so now we just use your PR since it has these changes in it too?
Should I close this one?

**Comment by chrisguida** [comment]
No, just merge #21 then #22

**Pull request merged**
